#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := static-ip

EXTRA_COMPONENT_DIRS = components/protocol_examples_common

include $(IDF_PATH)/make/project.mk

